### PR TITLE
Buf fixes and improvements

### PR DESCRIPTION
**Pull request by streamingdv**
+) Fix NVDXInteropCanvasImpl
+) Make dispose boolean volatile

Fix for point 1) and 2) mentioned here
https://github.com/husker-dev/openglfx/discussions/55#discussioncomment-7647419

### CODE REVIEW

**Comment by husker-dev** [comment]
Is ```context.makeCurrent()``` necessary? 
It worked without them.

**Comment by husker-dev** [comment]
Thanks for volatile, I completely forgot about it

**Comment by streamingdv** [comment]
@husker-dev yes it's necessary as otherwise resizing the canvas or disposing it will result in a black screen forever.

**Comment by streamingdv** [comment]
It fixes point 2) mentioned here

https://github.com/husker-dev/openglfx/discussions/55#discussioncomment-7647419

**Comment by husker-dev** [comment]
It's strange that this works on my PC. Although I added this line because it didn't work before.

Then let's leave it

**Comment by husker-dev** [comment]
I'll now make a big commit that will include your changes.

**Comment by husker-dev** [comment]
These are not final changes, now I’ll test them on macOS

**Comment by streamingdv** [comment]
@husker-dev i tested all other canvas elements (asynchronous and standard ones) except MacOS. The issue with context.makeCurrent() only happens when with NVDXInteropCanvasImpl but when I include this line again it will work as before. Not sure why though. If you include my commits in your next one that's fine for me as well.

**Pull request closed without merging**
